### PR TITLE
Adding sport_delete and eventgroup_delete

### PR DESCRIPTION
**Pull request by MischaD**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
@pbattu123 please review

**Comment by sschiessl-bcp** [comment]
@MischaD please resolve the conflict

**Comment by pbattu123** [comment]
I have reviewed the updates and everything looks fine except the following things.
1) Looks like eventgroup_delete method needs to be added in python-peerplays library.
2) Need to handle a scenario where sport delete proposal is pending and user try to delete corresponding event group(I didn't get a chance to test this)

**Comment by sschiessl-bcp** [comment]
@MischaD which python-peerplays version is required? Please add a ">=" in the requirements.

Please not that this might create issues due to https://github.com/peerplays-network/bos-mint/issues/19

**Comment by MischaD** [comment]
>         2. Need to handle a scenario where sport delete proposal is pending and user try to delete corresponding event group(I didn't get a chance to test this)
You are right, in a potential scenario where the user deletes a sport and the eventgroup_delete operation is still pending, the proposal stays pending even though the eventgroup is already deleted. 
Nevertheless handling this situation is not supposed to be part of this pull request as this is not a very useful thing to do and the current amount of users is very limited and they know what they're doing.

**Pull request closed without merging**
